#KafkaAutoConfiguration.java read this file

spring:
  profiles:
    active: local

---

spring:
  profiles: local
  kafka:
    default-topic: library-events
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
    #admin is used for kafkaAdmin
    admin:
      properties:
        bootstrap.servers: localhost:9092

---

spring:
  profiles: dev
  kafka:
    producer:
      bootstrap-servers: dev:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer